import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
test('desktop controls, spotlight, internal profiles, calendar persistence and full viewport', async ({ page }) => {
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 const dock=page.getByRole('navigation',{name:'Dock',exact:true});
 await expect(page.locator('.desktop-files')).toHaveCount(0);
 await expect(dock.getByRole('button',{name:'Projects',exact:true})).toHaveCount(0);
 await expect(dock.getByRole('button',{name:'Preview',exact:true})).toHaveCount(0);
 await expect(dock.getByRole('button',{name:'About Hamid',exact:true})).toHaveCount(0);
 await expect(page.locator('.welcome-hero')).toBeVisible();
 const clockMaterial = await page.locator('.clock-widget').first().evaluate(el=>getComputedStyle(el).backgroundColor);
 expect(clockMaterial).toBe(await page.locator('.calendar-widget').first().evaluate(el=>getComputedStyle(el).backgroundColor));
 await page.getByRole('button',{name:'Control Center',exact:true}).click();
 for(const name of ['Wi-Fi','Bluetooth','AirDrop']) {
  const control=page.getByRole('button',{name:`Toggle ${name}`,exact:true});
  const before=await control.getAttribute('aria-pressed'); await control.click();
  await expect(control).toHaveAttribute('aria-pressed',before==='true'?'false':'true');
  await control.click(); await expect(control).toHaveAttribute('aria-pressed',before);
 }
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Spotlight',exact:true}).click();
 await page.getByRole('textbox',{name:'Search apps'}).fill('github');
 const results=page.locator('.spotlight-results');
 await expect(results.getByRole('button').first()).toContainText('GitHub');
 await expect(results).not.toContainText('Safari');
 expect(await page.locator('.spotlight-backdrop').evaluate(e=>getComputedStyle(e).backdropFilter)).toContain('blur');
 await fs.mkdir('artifacts/qa',{recursive:true});
 await page.screenshot({path:'artifacts/qa/refinement-spotlight.png'});
 await page.keyboard.press('Enter');
 await expect(page.locator('.github-app')).toBeVisible();
 expect(page.context().pages()).toHaveLength(1);
 await expect(page.locator('.gh-toolkit-grid img')).toHaveCount(9);
 await expect.poll(() => page.locator('.gh-toolkit-grid img').evaluateAll(images=>images.every(img=>img.complete && img.naturalWidth>0))).toBe(true);
 await page.screenshot({path:'artifacts/qa/refinement-github.png'});
 await page.locator('.gh-tabs').getByRole('button',{name:'Toolkit',exact:true}).click();
 await expect(page.locator('.gh-toolkit-grid')).toBeInViewport();
 await page.screenshot({path:'artifacts/qa/refinement-github-toolkit.png'});
 await page.locator('.gh-work').getByRole('button',{name:'All projects'}).click();
 await expect(page.getByRole('dialog',{name:'Projects',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Close Projects',exact:true}).click();
 await dock.getByRole('button',{name:'GitHub',exact:true}).click();
 await page.locator('.gh-tabs').getByRole('button',{name:'Overview',exact:true}).click();

 const github=page.getByRole('dialog',{name:'GitHub',exact:true});
 const original=await github.boundingBox();
 await page.getByRole('button',{name:'Maximize GitHub',exact:true}).click();
 const full=await github.boundingBox(); expect(full.x).toBe(0); expect(full.y).toBe(0); expect(full.width).toBe(1440); expect(full.height).toBe(900);
 await page.screenshot({path:"artifacts/qa/refinement-github-fullscreen.png"});
 await page.getByRole('button',{name:'Maximize GitHub',exact:true}).click();
 expect((await github.boundingBox()).width).toBe(original.width);
 await page.locator('.github-app').getByRole('button',{name:'Get in touch'}).click();
 await expect(page.locator('.contacts-app')).toContainText('hamidshaikhy1382@gmail.com');
 await expect(page.locator('.contact-row').getByRole('link',{name:'+98 937 389 1553',exact:true})).toHaveAttribute('href','tel:+989373891553');
 await page.screenshot({path:'artifacts/qa/refinement-contacts.png'});
 await dock.getByRole('button',{name:'Calendar',exact:true}).click();
 await page.getByRole('button',{name:'New Event',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Review portfolio');
 await page.getByRole('button',{name:'Add event',exact:true}).click();
 await expect(page.locator('.calendar-event')).toContainText('Review portfolio');
 await page.getByRole('button',{name:'Next month',exact:true}).click();
 await expect(page.locator('.calendar-event')).toHaveCount(0);
 await page.getByRole('button',{name:'Previous month',exact:true}).click();
 await page.screenshot({path:'artifacts/qa/refinement-calendar.png'});
 await page.reload(); await dock.getByRole('button',{name:'Calendar',exact:true}).click();
 await expect(page.locator('.calendar-event')).toContainText('Review portfolio');
 await page.getByRole('button',{name:'Delete Review portfolio',exact:true}).click();
 await expect(page.locator('.calendar-event')).toHaveCount(0);
 const emptyDay=page.locator('.calendar-cell:not(.outside) .calendar-day-area').nth(10);
 const selectedDate=(await emptyDay.getAttribute('aria-label')).replace('Add event on ','');
 const dayRect=await emptyDay.boundingBox();
 await emptyDay.click({position:{x:12,y:dayRect.height-12}});
 await expect(page.getByLabel('Date',{exact:true})).toHaveValue(selectedDate);
 await page.getByLabel('Title',{exact:true}).fill('Added from empty space');
 await page.getByRole('button',{name:'Add event',exact:true}).click();
 await expect(page.locator('.calendar-event')).toContainText('Added from empty space');
 await page.getByRole('button',{name:'Delete Added from empty space',exact:true}).click();
 await expect(page.locator('.calendar-event-form')).toHaveCount(0);
 await dock.getByRole('button',{name:'Settings',exact:true}).click();
 await page.locator('.settings-sidebar').getByRole('button',{name:'Wallpaper'}).click();
 await page.getByRole('button',{name:'Aurora',exact:true}).click();
 await expect(page.getByRole('button',{name:'Aurora',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.reload();
 expect(await page.locator('.wallpaper-light').getAttribute('style')).toContain('aurora.jpg');
 await dock.getByRole('button',{name:'Calculator',exact:true}).click();
 const calc=page.locator('.calculator-app'); await calc.getByRole('button',{name:'7',exact:true}).click(); await calc.getByRole('button',{name:'+',exact:true}).click(); await calc.getByRole('button',{name:'3',exact:true}).click(); await calc.getByRole('button',{name:'=',exact:true}).click();
 await expect(calc.getByLabel('Calculator display')).toHaveText('10');
 await page.screenshot({path:'artifacts/qa/refinement-calculator.png'});
 await page.setViewportSize({width:390,height:844});
 await page.reload();
 await page.locator('.ios-home').getByRole('button',{name:'GitHub',exact:true}).click();
 await expect(page.locator('.gh-hero')).toBeVisible();
 expect(await page.locator('.github-app').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
 await page.screenshot({path:'artifacts/qa/refinement-github-mobile.png'});
 expect(errors).toEqual([]);
});
