import { useState } from "react";
import { Sun, Moon, Palette, Accessibility, Info, ChevronRight, Image, Dock, Check } from "lucide-react";
import { useOS } from "../state/os";
import { asset } from "../lib/assets";
import { wallpapers } from "../lib/wallpapers";
const pages = [{ id: "appearance", name: "Appearance", icon: Palette }, { id: "wallpaper", name: "Wallpaper", icon: Image }, { id: "dock", name: "Dock & Motion", icon: Dock }, { id: "accessibility", name: "Accessibility", icon: Accessibility }, { id: "about", name: "About macfolio", icon: Info }];
export default function Settings() {
  const os = useOS(); const [page, setPage] = useState("appearance");
  return <div className="settings-app"><aside className="settings-sidebar"><div className="settings-profile"><img src={asset("assets/avatar.png")} alt="" /><span><strong>Hamid Shaikhy</strong><small>Personal desktop</small></span></div>{pages.map(({ id, name, icon: Icon }) => <button key={id} className={id === page ? "selected" : ""} onClick={() => setPage(id)}><Icon size={18} />{name}<ChevronRight size={14} /></button>)}</aside>
    <main className="settings-body"><h2>{pages.find(p => p.id === page)?.name}</h2>
    {page === "appearance" ? <><section className="settings-group"><h3>Appearance</h3><div className="appearance-options">{(["light", "dark"] as const).map(t => <button key={t} aria-pressed={os.theme === t} className={os.theme === t ? "selected" : ""} onClick={() => os.setTheme(t)}><div className={`appearance-preview ${t}`}><span /><span /><span /></div><span>{t === "light" ? <Sun size={15} /> : <Moon size={15} />}{t === "light" ? "Light" : "Dark"}{os.theme === t && <Check size={14} />}</span></button>)}</div><p>Your wallpaper and all applications follow your appearance.</p></section><section className="settings-group"><label className="setting-row">Display brightness<input aria-label="Brightness setting" type="range" min=".35" max="1" step=".01" value={os.brightness} onChange={e => os.setBrightness(Number(e.target.value))} /></label><label className="setting-row">Music volume<input aria-label="Volume setting" type="range" min="0" max="1" step=".01" value={os.volume} onChange={e => os.setVolume(Number(e.target.value))} /></label><label className="setting-row">Focus<input className="switch" type="checkbox" checked={os.focusMode} onChange={os.toggleFocus} /></label><p>Brightness adjusts this page. Focus hides nonessential notifications.</p></section></>
    : page === "wallpaper" ? <section className="settings-group"><h3>Choose your view</h3><div className="wallpaper-gallery">{wallpapers.map(w => <button key={w.id} aria-label={w.name} aria-pressed={os.wallpaper === w.id} onClick={() => os.setWallpaper(w.id)}><img src={asset(`assets/wallpapers/${w.preview}.jpg`)} alt={w.name}/><span>{w.name}{os.wallpaper === w.id && <Check size={15}/>}</span></button>)}</div><p>Your wallpaper is saved independently of light and dark appearance.</p></section>
    : page === "dock" ? <section className="settings-group"><label className="setting-row">Dock size<input aria-label="Dock size" type="range" min="36" max="64" step="1" value={os.dockSize} onChange={e => os.setDockSize(Number(e.target.value))} /></label><label className="setting-row">Magnification<input className="switch" type="checkbox" checked={os.dockMagnification} onChange={e => os.setDockMagnification(e.target.checked)} /></label><label className="setting-row">Reduce Motion<input className="switch" type="checkbox" checked={os.reducedMotion} onChange={e => os.setReducedMotion(e.target.checked)} /></label><p>The Dock adapts to your screen. Reduce Motion also disables magnification.</p></section>
    : page === "accessibility" ? <section className="settings-group"><label className="setting-row">Reduce Motion<input className="switch" type="checkbox" checked={os.reducedMotion} onChange={e => os.setReducedMotion(e.target.checked)} /></label><p>Your browser’s motion preference is also respected. Use Tab to move through controls; Enter to open a selected file; arrow keys to navigate Finder, Spotlight and Chess.</p><dl className="shortcut-list"><div><dt>Spotlight</dt><dd>Ctrl / Cmd + Space</dd></div><div><dt>New Note</dt><dd>Ctrl / Cmd + N</dd></div><div><dt>Close Window</dt><dd>Ctrl / Cmd + W</dd></div><div><dt>Lock Screen</dt><dd>Ctrl + Cmd + Q</dd></div></dl></section>
    : <section className="settings-group about-system"><div className="system-mark">m</div><h3>macfolio</h3><p>Version 2.0</p><p className="persian" dir="rtl">پورتفولیوی تعاملی حمید شیخی؛ محیط شخصی مرور پروژه‌ها، رزومه و مهارت‌ها.</p><dl><div><dt>Location</dt><dd>Tehran, Iran</dd></div><div><dt>Time zone</dt><dd>Asia/Tehran</dd></div><div><dt>Storage</dt><dd>On this device</dd></div></dl><button className="text-button" onClick={() => os.openApp("github")}>GitHub / hamidshaikhy</button></section>}
    </main></div>;
}
